### ISSUE TITLE
langrank_predict.py for multiple tasks

### ISSUE THREAD

**Issue by neubig** [neulab/langrank#3]
Currently it seems that `langrank_predict.py` only works for the MT task, while in our paper we support 4 different tasks. Both the code and the README should probably explain how to do more tasks. (CC: @xiamengzhou, @yuhsianglin)

**Comment by antonisa** [comment]
Fixed the code (latest commit on master), need to update the README

**Comment by yuhsianglin** [comment]
Updated README.

**Comment by neubig** [comment]
Awesome, thanks!
