### ISSUE TITLE
There are two pre-trained parsing models?

### ISSUE THREAD

**Issue by neubig** [neulab/langrank#5]
Seems like there are both "DEP" and "Parsing", which is a bit confusing:
https://github.com/neulab/langrank/tree/master/pretrained

(CC: @antonisa, @xiamengzhou)

**Comment by antonisa** [comment]
Ah, in order to keep with the paper's notation I suggest we stick with "DEP",
but I think that the model under "Parsing" is the one trained on _all_ languages,
and hence the one we want. @xiamengzhou can confirm before I make any changes?

**Comment by xiamengzhou** [comment]
Yes, I've moved the model under Parsing to the DEP directory and deleted the Parsing directory.
