### ISSUE TITLE
Upload raw scores that went into training the model

### ISSUE THREAD

**Issue by neubig** [neulab/langrank#6]
It seems that the raw scores that went into training the model is not available through this repository (e.g. a TSV or whatever file with all the training/task language pairs). I think they should be. (CC: @antonisa, @xiamengzhou)

Also, I created a spreadsheet here where we can upload this data in an easy-to-browse format:
https://docs.google.com/spreadsheets/d/1yo9Zlnk_oMRshZeUMCHQmztnuC6VOCnP0wsgD7adRYQ/edit?usp=sharing

Once the data is available through the repository, I'd be happy to curate it into the necessary format to upload.

**Comment by antonisa** [comment]
I added the Entity Linking and the Dependency Parsing results,
only the POS-tagging ones are missing, but I don't seem to have them anywhere.

**Comment by yuhsianglin** [comment]
I added POS results that Junxian shared previously (source: https://docs.google.com/spreadsheets/d/1z52NB6EHgWIAu8G08nQVmyweuK3e-X1rwgo_NpOM0tk/edit#gid=0).

**Comment by neubig** [comment]
Awesome! It'd be nice to have all of these formatted in the same way if possible. If either of you could do this that'd be appreciated, but if not I can do it later.

**Comment by neubig** [comment]
Fixed the formatting!

**Comment by neubig** [comment]
Awesome! It'd be nice to have all of these formatted in the same way if
possible. If either of you could do this that'd be appreciated, but if not
I can do it later.

Graham
